#!/bin/bash

# This topic is IF Else Statement with Random numbers generated by system concept.



system_number=$RANDOM 
no_of_chances=1
for (( ; ; )) 
do 
read -p "this your chance no: $no_of_chances,guess my number: " user_number

if [ $user_number -eq $system_number ] 
then 
	echo "your guess is correct"
	echo "you gues this with  $no_my_chances so many chances"
	break
else 
	
	echo "your guess is wrong"
	if [ $user_numer -ge $system_number ]
	then 
	   echo "please enter lesser value then $user_number"
	else 
	   echo "plese enter higher value then $user_number"
	fi
fi
	no_of_chances=$((no_of_chances+1)) 


done 

